### PR TITLE
use maven-dependency-plugin for libraries in maven repository

### PR DESCRIPTION
**Pull request by timeraider4u**
use maven-dependency-plugin for libraries in maven repository

### CODE REVIEW

**Comment by HSorensen** [comment]
Is it justified to move from 2 LOC to 34 LOC? 
What does it bring ?

**Comment by timeraider4u** [comment]
I would agree to it, as it is the same as the solution in the antlr4ide.test/pom.xml and it can save bandwidth by only downloading the JAR files when they are not already in the local repository.

**Comment by HSorensen** [comment]
Ok, agreed. Better to be consistent.
Pls see my review comment.

**Comment by timeraider4u** [comment]
yes, you are right. fixed in latest commit.

**Comment by HSorensen** [comment]
I did a quick search for org.abego and treelayout.core. Please make sure you test this with the parse tree view.

I think there are a few more updates to be done:
Can you check the generated ant file 
`/antlr4ide.core/target/antrun/build-main.xml`
contains the correct jar-file name

image

content in my workspace
```xml
<get usetimestamp="true" 
     skipexisting="true" 
     src="http://repo1.maven.org/maven2/org/abego/treelayout/org.abego.treelayout.core/1.0.1/org.abego.treelayout.core-1.0.1.jar" 
     dest="${workDir}/lib/treelayout.core-1.0.1.jar"/>
```

also
image

please pay attention to the `.classpath` updates to ensure all entries are relative to the project and all entries are included in the project.

**Comment by timeraider4u** [comment]
the file "antlr4ide/antlr4ide.core/target/antrun/build-main.xml" is generated by running the maven-antrun-plugin. The content of the <target>...</target> tags is written to an xml file. Therefore, if you clean the target-folder it should be updated.

I will check the other files later...

**Comment by timeraider4u** [comment]
mhm, I cannot confirm your observations. If I take a look at antlr4core/META-INF/MANIFEST.mf I find Bundle-ClassPath: lib/org.abego.treelayout.core-1.0.1.jar,
So it should be okay. Is it possible that you are on the wrong branch (these commits have not been merged yet and are, therefore, only available in the current master-branch of my Github fork)?

**Comment by HSorensen** [comment]
Thanks

**Pull request merged**
