### PR TITLE
Issue #71: Override project location

### PR DESCRIPTION
**Pull request by HSorensen**
This is a nasty hack that basically bypass the code generation framework.
Solves issue #71 

This pull request bypass the generated Antlr4NewProjectWizard class by pointing the plugin.xml extension point to the hand written Antlr4NewProjectWizardV2.java file. The generated file is still there, but is not being used.

Once we figure out how to control the code generation we can revisit this.

The file 
`/antlr4ide/antlr4ide.core/src/main/java/com/github/jknack/antlr4ide/GenerateAntlr4.mwe2`
contains the workflow that among many other things generates the new project wizard.

The generated wizard does not contain logic to store the project location information if the user decide to override the default location.

This pull request basically use a hand crafted new wizard code and change the wizard extension in the `plugin.xml` to use the new java code.

### CODE REVIEW

**Comment by arifogel** [comment]
Let me ask a more general question:
Where is code generation performed in this project? In each case, why is code generation preferable to hand-written code? What work is being saved?

**Comment by timeraider4u** [comment]
Well, the first commit "Fix comment for project wizard" can be pulled without any risk ;-).

**Comment by HSorensen** [comment]
@arifogel look at #71 for details to code generation. It is a big black box to me.

**Comment by timeraider4u** [comment]
from my point of view the `fragment = projectWizard.SimpleProjectWizardFragment auto-inject {
        generatorProjectName = "${projectName}.generator"
        fileExtension = fileExtensions
      }`
can either be commented out or even be removed. I do not see a reason why it would be required.

**Comment by HSorensen** [comment]
@timeraider4u I tried that but there are some generated artifacts used elsewhere so I did the brutal version instead. It would be the best if we can figure out how to eliminate the code generation for the project wizard. It really does not make any sense to keep generating the code. Unless I am missing something.

**Comment by HSorensen** [comment]
I am thinking to merge this PR. To resolve the xtend stuff will like take considerable amount of time, and I really want to close #71.

I will see of I can change the name of the generated wizard to Antlr4NewProjectWizardDONTUSE to avoid any accidental usage. 

Thoughts ?

**Comment by timeraider4u** [comment]
From my side: I do not have any objections against it ;-).

**Pull request merged**
